config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_up: 'registration' },
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations'
             }

  root 'static_pages#landing_page'

  resources :users, only: %i[index show edit update destroy] do
    member do
      post :resend_invitation
    end
  end

  resources :classrooms

  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  validates :name, presence: true
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: %i[show edit update destroy]

  def index
    @classrooms = Classroom.all
  end

  def show; end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to classrooms_path, notice: 'Classroom was created' }
      else
        render_turbo_stream_error
        format.turbo_stream do
          render turbo_stream: prepend_flash
        end
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to classrooms_path, notice: 'Classroom was updated' }
      else
        render_turbo_stream_error
        format.turbo_stream do
          render turbo_stream: prepend_flash
        end
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @classroom.destroy
    flash.now[:notice] = 'Classroom was deleted'

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@classroom),
          prepend_flash
        ]
      end
      format.html { redirect_to classrooms_path, notice: 'Classroom was deleted' }
    end
  end

  private

  def set_classroom
    @classroom = Classroom.find(params[:id])
  end

  def classroom_params
    params.require(:classroom).permit(:name)
  end

  def render_turbo_stream_error
    flash.now[:alert] = @classroom.errors.full_messages.join('; ')
  end
end

app/views/classrooms/_classroom.html.slim
tr.align-middle id="#{dom_id(classroom)}"
  td
    = link_to classroom.name, classroom, class: 'orange-link', data: { turbo: false }

  td.text-center
    = link_to icon('far fa-edit'), edit_classroom_path(classroom), class: 'orange-link me-2', data: { turbo: false }
    = link_to icon('far fa-trash-alt'), classroom, class: 'orange-link', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

app/views/classrooms/_form.html.slim
.row
  .col-md-12.col-xxl-10.m-auto.mt-md-2
    .card.mt-3
      .card-header.pb-0
        .d-flex
          div
            = link_to icon('fa fa-arrow-left'), classrooms_path, class: 'btn btn-sm btn-outline-secondary me-2'
          h4 = classroom.persisted? ? 'Edit classroom' : 'New classroom'

      = form_with model: classroom do |f|
        = render 'shared/errors', resource: classroom

        .card-body
          .mb-3
            = f.label :name, class: 'form-label'
            span.ps-1.text-danger *
            = f.text_field :name, class: 'form-control form-control-sm'

          = f.submit class: 'btn btn-sm btn-primary'

app/views/classrooms/edit.html.slim
= render 'form', classroom: @classroom

app/views/classrooms/index.html.slim
.row
  .col-md-12.col-xxl-10.m-auto.mt-md-2
    .d-flex.my-1.justify-content-between
      h4 Classrooms
      div
        = link_to 'Add classroom', new_classroom_path, class: 'btn btn-sm btn-primary'
    = turbo_frame_tag 'classrooms' do
      .table-responsive
        table.table.table-hover.table-bordered
          thead
            tr.bg-light
              th Name
              th.text-center style='width: 100px' Actions

          = render @classrooms

app/views/classrooms/new.html.slim
= render 'form', classroom: @classroom

app/views/classrooms/show.html.slim
container
  .row.justify-content-around.pt-2
    .d-flex.my-1
      div
        = link_to icon('fa fa-arrow-left'), classrooms_path, class: 'btn btn-sm btn-outline-secondary me-2'

      h4 = @classroom.name

    .col-md-12
      table.table.table-bordered
        tr
          th Name
          td = @classroom.name
        tr
          th Classroom updated at:
          td = l @classroom.updated_at, format: :long
        tr
          th Classroom created at:
          td = l @classroom.created_at, format: :long

      div
        = link_to 'Back', classrooms_path, class: 'btn btn-outline-secondary btn-sm me-1'

        = link_to 'Edit', edit_classroom_path(@classroom), class: 'btn btn-outline-primary btn-sm me-1'

        = link_to 'Delete', @classroom, class: 'btn btn-outline-danger btn-sm',
          data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }