config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_up: 'registration' },
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations'
             }

  root 'static_pages#landing_page'

  resources :users, only: %i[index show edit update destroy] do
    member do
      post :resend_invitation
    end
  end

  resources :classrooms

  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/models/user.rb
class User < ApplicationRecord
  include Roleable

  devise :invitable, :database_authenticatable, :registerable, :trackable,
         :rememberable, :validatable, :omniauthable, omniauth_providers: [:github]

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def self.from_omniauth(access_token)
    user = User.where(email: access_token.info.email).first

    user ||= User.create(
      email: access_token.info.email,
      password: Devise.friendly_token[0, 20]
    )
    user.provider  = access_token.provider
    user.uid       = access_token.uid
    user.username  = access_token.info.nickname unless user.username.present?
    user.name      = access_token.info.name unless user.name.present?
    user.image_url = access_token.info.image
    user.save

    user
  end

  after_create do
    # assign default role
    self.update(student: true)
  end

  def to_s
    email
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    handle_auth 'Github'
  end

  def handle_auth(kind)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = t 'devise.omniauth_callbacks.success', kind: kind
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.auth_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path, alert: t('devise.omniauth_callbacks.failure')
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  invisible_captcha only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy resend_invitation require_admin_or_inviter require_admin_or_owner]
  before_action :require_admin, only: %i[destroy]
  before_action :require_admin_or_inviter, only: %i[resend_invitation]
  before_action :require_admin_or_owner, only: %i[show edit update]

  def index
    @users = User.order(:created_at)
  end

  def show; end

  def edit; end

  def update
    @user.update(user_params)
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      respond_to do |format|
        render_turbo_stream_error
        format.turbo_stream do
          render turbo_stream: prepend_flash
        end
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @user != current_user
      @user.destroy
      redirect_to users_path, notice: 'User was destroyed'
    else
      respond_to do |format|
        flash.now[:alert] = 'Action Forbidden!'
        format.turbo_stream do
          render turbo_stream: prepend_flash
        end
      end
    end
  end

  def resend_invitation
    @user.invite!
    redirect_to @user, notice: 'Invitation were resent'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    list_allowed_params = []
    list_allowed_params += [:name] if current_user == @user || current_user.admin?
    list_allowed_params += [*User::ROLES] if current_user.admin?

    params.require(:user).permit(list_allowed_params)
  end

  def render_turbo_stream_error
    flash.now[:alert] = @user.errors.full_messages.join('; ')
  end

  def require_admin
    return if current_user.admin?

    redirect_to root_path, alert: 'Action Forbidden!'
  end

  def require_admin_or_inviter
    return if current_user.admin? || @user.invited_by == current_user

    redirect_to root_path, alert: 'Action Forbidden!'
  end

  def require_admin_or_owner
    return if current_user.admin? || current_user == @user

    redirect_to root_path, alert: 'Action Forbidden!'
  end
end

app/views/users/_user.html.slim
tr
  td = user.id
  td = link_to user, user, class: 'orange-link'
  td = user.active_roles.join(', ')

  - if current_user.admin?
    td.text-center
      = link_to icon('far fa-edit'), edit_user_path(user), class: 'orange-link me-2'
      = link_to icon('far fa-trash-alt'), user, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'orange-link'

app/views/users/edit.html.slim
.card.mt-3
  .card-header
    .h4.mb-0
      | Editing roles for
      =< @user

  .card-body
    = form_for @user do |f|
      = render 'shared/errors', resource: @user

      .mb-3
        = f.label :name, class: 'form-label'
        = f.text_field :name, class: 'form-control form-control-sm'

      - if current_user.admin?
        - User::ROLES.each do |role|
          label
            => f.check_box role
            = role.to_s.humanize
          br

      .mt-2
        = f.submit class: 'btn btn-sm btn-primary me-1'
  .card-footer
    = link_to 'Cancel', @user, class: 'blue-link'

app/views/users/index.html.slim
h3.mt-3 All Users (#{@users.size})

.table-responsive
  table.table.table-bordered.table-hover
    thead
      tr.bg-light
        th ID
        th Email
        th Roles
        - if current_user.admin?
          th.text-center Actions
    tbody
      = render @users

app/views/users/show.html.slim
.card.mt-3
  .card-header
    h3.mb-0 User page

  .card-body
    - if @user.image_url.present?
      .mb-2
        = image_tag @user.image_url, size: 200

    .mb-2
      span.fw-semibold> Email:
      = @user

    .mb-2
      span.fw-semibold> Name:
      = @user.name ? @user.name : '—'

    - if @user.username.present?
      .mb-2
        span.fw-semibold> Github username:
        = @user.username

    - if @user.uid.present?
      .mb-2
        span.fw-semibold> Uid:
        = @user.uid

    .mb-2
      span.fw-semibold> Roles:
      = @user.active_roles.join(", ")

    .mb-2
      span.fw-semibold> Sign in count:
      = @user.sign_in_count

    .mb-2
      span.fw-semibold> Current sign in at:
      = @user.current_sign_in_at

    .mb-2
      span.fw-semibold> Last sign in at:
      = @user.last_sign_in_at

    .mb-2
      span.fw-semibold> Current sign in ip:
      = @user.current_sign_in_ip

    .mb-2
      span.fw-semibold> Last sign in ip:
      = @user.last_sign_in_ip

    - if @user.invited_by.present?
      .mb-2
        span.fw-semibold> Invited by:
        = @user.invited_by

    .mb-2
      span.fw-semibold> Create by invite:
      = boolean_label(@user.created_by_invite?)

    - if @user.created_by_invite?
      .mb-2
        span.fw-semibold> Is invitation accepted?:
        = boolean_label(@user.invitation_accepted?)

    - if current_user.admin? || @user.invited_by == current_user
      - if @user.created_by_invite? && !@user.invitation_accepted?
        = link_to 'Resend invitation', resend_invitation_user_path, data: { turbo_method: :post }, class: 'orange-link'

  .card-footer
    - if current_user.admin?
      = link_to 'All users', users_path, class: 'blue-link me-2'
      = link_to 'Edit', edit_user_path(@user), class: 'orange-link me-2'
      = link_to 'Delete', @user, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'red-link'
    - else
      = link_to 'Home', root_path, class: 'blue-link me-2'
      = link_to 'Edit', edit_user_path(@user), class: 'orange-link'