config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_up: 'registration' },
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations'
             }

  root 'static_pages#landing_page'

  resources :users, only: %i[index show edit update destroy] do
    member do
      post :resend_invitation
    end
  end

  resources :classrooms

  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/views/shared/_errors.html.slim
- if resource.present? && resource.errors.any?
  = content_tag :div, id: 'alert-flash',
    class: 'alert  alert-danger fade show align-items-center position-fixed top-0 end-0 mt-5 me-3',
    role: 'alert',
    data: { controller: 'autohide', resource_id: resource.id } do
    .row
      .col-auto
        - resource.errors.each do |error|
          = error.full_message
          br
      .col.text-end
        button.btn-close.ms-2 type='button' data-bs-dismiss='alert' aria-label='Close' data-autohide-target='close'

app/views/shared/_flash.html.slim
- if flash.any?
  - flash.each do |type, msg|
    - if type == 'alert'
      = content_tag :div, msg, id: 'alert-flash',
        class: 'alert  alert-danger fade show align-items-center position-fixed top-0 end-0 mt-5 me-3',
        role: :alert,
        data: { controller: 'autohide' } do
        .justify-content-around
          = msg
          button.btn-close.ms-2 type='button' data-bs-dismiss='alert' aria-label='Close' data-autohide-target='close'

    - else
      = content_tag :div, msg, id: 'notice-flash',
        class: 'alert alert-success alert-dismissible fade show align-items-center position-fixed top-0 end-0 mt-5 me-3',
        role: :alert,
        data: { controller: 'autohide' } do
        .justify-content-around
          = msg
          button.btn-close.ms-2 type='button' data-bs-dismiss='alert' aria-label='Close' data-autohide-target='close'

app/views/shared/_footer.html.slim
.border-top.bg-light
  .container
    .my-2
      = link_to privacy_policy_path, class: 'primary-link' do
        i.fa-solid.fa-file-lines.pe-1.d-none.d-sm-inline
        | Privacy Policy

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-md.sticky-top.navbar-light.border-bottom.header
  .container-fluid
    .navbar-brand
      = link_to root_path, class: 'nav-link', title: 'Home page' do
        i.fa-solid.fa-graduation-cap.pe-1
        | School App
    button.navbar-toggler[type='button' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation']
      span.navbar-toggler-icon

    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        - if user_signed_in? && current_user.admin?
          li.nav-item.me-3
            = link_to users_path, class: 'primary-link' do
              i.fa.fa-users.pe-1.d-none.d-sm-inline
              | Users
          i.nav-item.me-3
            = link_to classrooms_path, class: 'primary-link' do
              i.fa.fa-book.pe-1.d-none.d-sm-inline
              | Classrooms
        - if user_signed_in?
          li.nav-item.me-3
            = link_to new_user_invitation_path, class: 'primary-link' do
              i.fa.fa-user-plus.pe-1.d-none.d-sm-inline
              | Invite user
      ul.navbar-nav.ms-auto.me-md-2
        - if user_signed_in?
          a#navbarDropdown.nav-item.dropdown-toggle.text-end.mb-md-0.mb-1.primary-link[href='#' role='button' data-bs-toggle='dropdown'aria-expanded='false']
            = current_user.email
          ul.dropdown-menu.dropdown-menu-lg-end.me-md-3.mt-0[aria-labelledby='navbarDropdown']
            li
              = link_to user_path(current_user), class: "dropdown-item" do
                .fa.fa-user.pe-1
                span Profile
            li
              = link_to destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item' do
                .fa.fa-sign-out-alt.pe-1
                span Logout
        - else
          = link_to new_user_session_path, class: 'primary-link me-3' do
            i.fa-solid.fa-right-to-bracket.d-none.d-sm-inline>
            | Sign in
          = link_to new_user_registration_path, class: 'primary-link' do
            i.fa-solid.fa-user-plus.d-none.d-sm-inline>
            | Sign up